import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import InitReferenceData from './components/initReferenceData';
import { ReferenceProvider } from './context/referenceContext';
import { VisualProvider } from './context/visualContextProvider';
import './globals.css';

// const geistSans = Geist({
//     variable: '--font-geist-sans',
//     subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//     variable: '--font-geist-mono',
//     subsets: ['latin'],
// });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full bg-white">
            <body className="h-full">
                <ReferenceProvider>
                    <VisualProvider>
                        <InitReferenceData />
                        {children}
                    </VisualProvider>
                </ReferenceProvider>
            </body>
        </html>
    );
}
